---
title: "FinalProject"
author: "Overachievers"
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(countrycode)
library(RColorBrewer)
library(tmap)
library(rgdal)
library(leaflet)
library("sf")
library("raster")
library("sp")
#install.packages("rnaturalearth")
library(rnaturalearth)
#install.packages(rgeos)
library(rgeos)
```

```{r pulling-in-data-sets}
happiness <- read_csv("/cloud/project/data/world-happiness/2015.csv")
drug_spending <- read_csv("/cloud/project/data/pharmaceutical-drug/pharmaceutical_data_csv.csv")
```

```{r cleaning-data-sets}
drug_spending <- drug_spending %>%
  filter(TIME == 2015) %>%
  mutate(Country = countrycode(LOCATION, "iso3c", "country.name")) %>%
  mutate(Continent = countrycode(LOCATION, "iso3c", "continent"))
```

```{r cleaning-happiness-dataset}
happiness$Country_title = str_to_title(happiness$Country)

happiness %>%
  mutate(Continent = countrycode(Country_title, "country.name", "continent"))
```

```{r}
combined <- inner_join(happiness, drug_spending, by = "Country")
```

```{r finding-drug-spending-by-country}
drug_spending %>%
    ggplot(aes(x = LOCATION, y = TOTAL_SPEND)) +
    geom_jitter() +
    labs(x = "Countries",
         y = "Total spending on pharmaceutical drugs", 
        title = "Total spending on pharmaceutical drugs in 2015 by countries")
```
```{r create-EU-non_EU-vector}

x <- c("non-EU", "non-EU", "EU", "non-EU", "EU", "EU", "EU", "EU", "Outside-Europe", "Outside-Europe", "EU", "EU", "EU", "Outside-Europe", "EU", "EU", "EU", "EU", "Outside-Europe", "EU", "EU", "EU", "EU", "non-EU", "EU", "EU", "EU", "EU", "EU")
```


```{r adding-new-column-of-EU-nonEU}
combined$NonEU_EU <- x
```


```{r filtering-data-to-European-Countries }
european_combined <- combined %>%
  filter(NonEU_EU != "Outside-Europe")
```

```{r linear-regresssion-PC_GDP-Happiness-Score}
gdp_happiness_correlation <- 
  linear_reg() %>%
  set_engine("lm") %>%
  fit(`Happiness Score` ~ PC_GDP + factor(NonEU_EU), data = european_combined) %>%
  tidy()
gdp_happiness_correlation
```

```{r finding-linear-regression-GDP-Happiness-Score}
GDP_happiness.lm = lm(`Happiness Score` ~ PC_GDP, data = european_combined) 
GDP_Hapiness.res = resid(GDP_happiness.lm)
GDP_Hapiness.res
```

```{r}
augmented_fit_lm <- augment(gdp_happiness_correlation$fit)
augmented_fit_lm

finaldf <- cbind(european_combined$Country, augmented_fit_lm )
finaldf
```

```{r rename-country-column}
finaldf <- rename(finaldf, Country = `european_combined$Country`)
```


```{r add-geometry-to-df}
europe <- ne_countries(continent = 'europe', returnclass="sf")
europe_map_df<- full_join(finaldf, europe, by = c("Country" = "sovereignt"))
```

```{r europe-map, echo=FALSE, warning=FALSE, out.height="30%", out.width="100%"}
map <- ggplot(europe_map_df) +
  geom_sf(aes(fill = .std.resid, geometry = europe_map_df$geometry)) +
  labs(title = "Happiness Score Residuals",
       x = "Longitude",
       y = "Latitude", 
       fill = "residuals") +
  xlim(-40, 50) +
  ylim(20, 85) +
  scale_fill_distiller(palette = "Spectral") +
  annotate(x = )

ggplotly(map) +
  layout(hoverlabel)
```
