---
title: What Makes You Happy
author: by Overachievers
output: github_document
---

## Summary

	For our project, we decided to examine whether or not certain predicting factors (importance of family, GDP percent spending on pharmaceuticals, and percent spending on healthcare) impacted countries’ happiness scores. We did this because for several years, there has been a world happiness report that measures the state of global happiness (Sustainable Development Solutions Network, 2017). The report utilizes a survey where citizens rate their own lives based on different factors. This includes family, freedom, health, economy and trust towards the government. This report is important because since it first came out in 2012, it gained global recognition from governments, organizations and civil society. The measurements of well-being could potentially be used to assess the progress of a nation, informing their policy-making decisions from happiness indicators measured in the report (World Happiness Report, 2013). This data set appealed to us because we were interested if a more concrete variable impacts such a subjective variable such as happiness score. We then needed to find this concrete variable and did so with the Pharmaceutical Drug Spending by Countries data set (Tunguz, 2021). This data set comprises GDP and the total healthcare spending on pharmaceuticals for many countries across multiple years. We then filtered the data sets to only include 2015 (as this was the year that we had for the Happiness data set) and merged the two data sets together. 

	After examining the data sets we came up with three main hypotheses. The first hypothesis was that non-western countries have higher family importance scores influencing happiness scores. Our second hypothesis was that the higher the percent of drug spending on GDP, the higher the percent spent on pharmaceutical drugs in healthcare. Our last hypothesis was that the higher the percent GDP spending on pharmaceuticals, the lower the happiness score of European countries. We then conducted different analyses to find confirming or disconfirming evidence. 

For our first hypothesis, we decided to just utilize the Happiness data set to see the potential significant differences between non-western and western countries in regards to family importance scores impacting overall happiness. We were interested in this analysis because through previous courses and the article “How East and West think in profoundly different ways”, which suggests that non-western countries have higher collectivistic values than western countries that typically tend to be more individualistic (Robson, 2017). This is the reason why we hypothesize that non-western countries have higher family importance scores influencing happiness scores. The first part of this analysis consisted of us creating a new variable that separated the countries into “Western” and “Non-Western”. We then used this variable to compare the correlation between family importance scores and overall happiness scores. We ran a linear regression analysis on both groups. Interestingly, family importance scores impacted Western countries more so than non-Western countries which refutes our first hypothesis. We then decided to take this analysis a step further and focus on European countries (We did this because our Pharmaceutical Spending data set was lacking data for most other continents). We decided to run another linear regression of family importance score and overall happiness score but this time we filtered the countries to only Europe and then grouped them by either EU or non-EU. We hypothesized that non-EU countries would be more collective in nature and therefore family importance would play a bigger role on overall happiness than EU countries. Interestingly, our linear regression equations came out equal, meaning that family importance impacted EU and non-EU countries equally which again refuted our hypothesis. 

For our second analysis, we decided to analyze the Pharmaceutical Drug Spending by Countries data set to see if  the higher the percentage of drug spending as a share of GDP, the higher the percentage spent on pharmaceutical drugs in healthcare among European countries. We thought this because data collected on drug spending would most likely be composed of legally obtained drugs, which are mostly pharmaceutical drugs. As a result, we propose that countries that are willing to spend more of their GDP on drugs will mostly have a higher percentage of drug spending in the healthcare industry. 

With our given datasets, we want to focus our analysis on the European countries. From our pharmaceutical drug spending dataset, we looked at the correlation between the percent of drug spending on healthcare vs Percent on GDP. We observed a positive correlation with a R squared value of 0.65

	For our final hypothesis we utilized the combined data set to see if percent GDP spending on pharmaceuticals has a negative effect on a country's happiness score among countries in Europe. We believe this because we think that countries with high spending percentages are potentially overmedicating their populations, therefore decreasing happiness. To examine this we ran a linear regression to examine the potential relationship. We found the line of best fit to be happiness score = 8.368 - 1.423(Percent GDP). This means that for each percent increase of GDP spending on pharmaceuticals, the happiness score drops 1.423. This at least shows preliminary evidence for accepting our hypothesis that the higher the percent GDP spending on pharmaceuticals, the lower the happiness score of European countries. We then decided to plot residuals from our line of best fit to see which countries scored higher or lower than we predicted. This highlighted several countries such as Switzerland (higher than expected), Estonia and Portugal (lower than expected). We then used plotly to plot the residuals on a map of Europe to visually highlight these differences. 
There are a number of limitations within this study. The first of which is that the merged data set is not a full representation of the world (as there were many countries missing from most continents besides Europe). If we had more time we would have liked to conduct this analysis again with more data (across more countries) if available. We would have especially liked to have found a Pharmaceutical Drug Spending by Countries data set that had more categories and the breakdown of the budget to conduct more niche analyses. Another limitation of this analysis was that happiness is such a subjective variable to measure, therefore it is hard to conclude how much GDP spending on pharmaceuticals actually impacted Happiness Scores. Correlation also does not equal causation. However, our high-level analyses showed preliminary evidence that higher percent GDP spending on pharmaceuticals negatively affects countries’ happiness scores. Future analyses should examine this in greater detail (with a more robust pharmaceutical spending data set) to see what factors of pharmaceutical spending are positive/negative in regards to countries’ happiness scores. Overall though, we are happy with our project plan and analyses and hope that future research examines this further. 



## Presentation

Our presentation can be found [here](presentation/presentation.html).

## Data

* Sustainable Development Solutions Network 2017, World Happiness Report, electronic dataset, Kaggle, viewed 01 October 2021, https://www.kaggle.com/unsdsn/world-happiness
* Tunguz, B 2021, Pharmaceutical Drug Spending by Countries, electronic dataset, Kaggle, viewed 01 October 2021, https://www.kaggle.com/tunguz/pharmaceutical-drug-spending-by-countries

## References

* Robson, D. (2017, January 19). How East and West think in profoundly different ways. BBC. https://www.bbc.com/future/article/20170118-how-east-and-west-think-in-profoundly-different-ways

* World Happiness Report. (2013, September 09). Report Calls On Policy Makers To Make Happiness A Key Measure And Target Of Development. https://worldhappiness.report/blog/report-calls-on-policy-makers-to-make-happiness-a-key-measure-and-target-of-development/

