---
title: "Working file"
author: "Overachievers - Yueh"
date: "11/7/2021"
output: html_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(countrycode)
library(tidymodels)
library(openintro)
```

```{r pulling-in-data-sets}
happiness <- read_csv("/cloud/project/data/world-happiness/2015.csv")
drug_spending <- read_csv("/cloud/project/data/pharmaceutical-drug/pharmaceutical_data_csv.csv")
```

```{r cleaning-data-sets}
drug_spending <- drug_spending %>%
  mutate(Country = countrycode(LOCATION, "iso3c", "country.name")) %>%
  mutate(Continent = countrycode(LOCATION, "iso3c", "continent"))
```

```{r summary-statistics-drug-spending}
drug_spending %>%
  drop_na(PC_HEALTHXP) %>%
  group_by(Continent) %>%
  summarise(min = min(PC_HEALTHXP), max = max(PC_HEALTHXP),
            mean = mean(PC_HEALTHXP), med = median(PC_HEALTHXP),
            sd = sd(PC_HEALTHXP), 
            q1 = quantile(PC_HEALTHXP, probs = 0.25),
            q3 = quantile(PC_HEALTHXP, probs = 0.75))
```

```{r finding-drug-spending-by-country}
drug_spending %>%
    drop_na(PC_HEALTHXP) %>%
    ggplot(aes(x = TIME, y = PC_HEALTHXP, na.rm = TRUE)) +
    geom_line() +
    # calculate the mean of y
    stat_summary(fun.y = "mean", colour = "red", size = 1, geom = "line") + 
    facet_wrap(~Continent) +
    labs(x = "Year",
         y = "Percent of drug spending on healthcare", 
        title = "Total spending on pharmaceutical drugs by countries")
```
```{r finding-drug-spending-by-country2}
drug_spending %>%
    drop_na(PC_HEALTHXP) %>%
    ggplot(aes(x = TIME, y = PC_HEALTHXP, colour = Country)) +
    geom_jitter() +
    # calculate the mean of y
    #stat_summary(fun.y = "mean", colour = "red", size = 1, geom = "line") + 
    facet_wrap(~Continent) +
    labs(x = "Year",
         y = "Percent of drug spending on healthcare", 
        title = "Total spending on pharmaceutical drugs by countries")
```

```{r finding-drug-spending-by-Americas}
drug_spending %>%
    drop_na(PC_HEALTHXP) %>%
    filter(Continent == "Americas") %>%
    ggplot(aes(x = TIME, y = PC_HEALTHXP, colour = Country)) +
    geom_line() +
    labs(x = "Year",
         y = "Percent of drug spending on healthcare", 
        title = "Total spending on pharmaceutical drugs by countries")
```

```{r finding-drug-spending-Asia}
drug_spending %>%
   # drop_na(PC_HEALTHXP) %>%
    filter(Continent == "Asia") %>%
    ggplot(aes(x = TIME, y = PC_HEALTHXP, colour = Country)) +
    geom_line() +
    labs(x = "Year",
         y = "Percent of drug spending on healthcare", 
        title = "Total spending on pharmaceutical drugs by countries")
```


```{r finding-drug-spending-Oceania}
drug_spending %>%
    #drop_na(PC_HEALTHXP) %>%
    filter(Continent == "Oceania") %>%
    ggplot(aes(x = TIME, y = PC_HEALTHXP, colour = Country)) +
    geom_line() +
    labs(x = "Year",
         y = "Percent of drug spending on healthcare", 
        title = "Total spending on pharmaceutical drugs by countries")
```

```{r finding-drug-spending-Europe}
drug_spending %>%
    #drop_na(PC_HEALTHXP) %>%
    filter(Continent == "Europe") %>%
    ggplot(aes(x = TIME, y = PC_HEALTHXP, colour = Country)) +
    geom_line() +
    labs(x = "Year",
         y = "Percent of drug spending on healthcare", 
        title = "Total spending on pharmaceutical drugs by countries")
```


```{r finding-gdp-spending-by-country}
drug_spending %>%
    drop_na(PC_GDP) %>%
    ggplot(aes(x = TIME, y = PC_GDP)) +
    geom_line() +
    # calculate the mean of y
    stat_summary(fun.y = "mean", colour = "red", size = 1, geom = "line") + 
    facet_wrap(~Continent) +
    labs(x = "Year",
         y = "Percent of drug spending GDP", 
        title = "Total spending on pharmaceutical drugs by countries")
```

```{r finding-drug-GDP-spending-by-country2}
drug_spending %>%
    #drop_na(PC_GDP) %>%
    ggplot(aes(x = TIME, y = PC_GDP, colour = Country)) +
    geom_jitter() +
    facet_wrap(~Continent) +
    labs(x = "Year",
         y = "Percent of drug spending based on GDP", 
        title = "Total spending on pharmaceutical drugs by countries")
```


```{r finding-GDP-drug-spending-by-Americas}
drug_spending %>%
    #drop_na(PC_GDP) %>%
    filter(Continent == "Americas") %>%
    ggplot(aes(x = TIME, y = PC_GDP, colour = Country)) +
    geom_line() +
    labs(x = "Year",
         y = "Percent of drug spending on GDP", 
        title = "Total spending on pharmaceutical drugs by countries")
```

```{r finding-GDP-drug-spending-Asia}
drug_spending %>%
   # drop_na(PC_HEALTHXP) %>%
    filter(Continent == "Asia") %>%
    ggplot(aes(x = TIME, y = PC_GDP, colour = Country)) +
    geom_line() +
    labs(x = "Year",
         y = "Percent of drug spending on GDP", 
        title = "Total spending on pharmaceutical drugs by countries")
```


```{r finding-GDP-drug-spending-by-Europe}
drug_spending %>%
    #drop_na(PC_GDP) %>%
    filter(Continent == "Europe") %>%
    ggplot(aes(x = TIME, y = PC_GDP, colour = Country)) +
    geom_line() +
    labs(x = "Year",
         y = "Percent of drug spending on GDP", 
        title = "Total spending on pharmaceutical drugs by countries")
```

```{r finding-GDP-drug-spending-Oceania}
drug_spending %>%
   # drop_na(PC_HEALTHXP) %>%
    filter(Continent == "Oceania") %>%
    ggplot(aes(x = TIME, y = PC_GDP, colour = Country)) +
    geom_line() +
    labs(x = "Year",
         y = "Percent of drug spending on GDP", 
        title = "Total spending on pharmaceutical drugs by countries")
```
```{r}
drug_spending2015 <- drug_spending %>%
                      filter(TIME == 2015)
```

```{r finding-GDP-healthXP-in-Europe-2015}
drug_spending2015 %>%
    filter(Continent == "Europe") %>%
    ggplot(aes(x = PC_GDP, y = PC_HEALTHXP, colour = Country)) +
    geom_point() +
    geom_smooth(method = "lm", 
              color = "black",
              size = 0.3,
              se = FALSE) +
    labs(x = "Percent of Drug Spending on GDP",
         y = "Percent of Drug Spending on Total Healthcare Spending", 
        title = "Pharmaceutical Drug Spending As A Share of Total Healthcare Spending & GDP",
        subtitle = "in European Countries")
```



```{r linear-regression}
GDP_HC_fit <- 
  linear_reg() %>%
  set_engine("lm") %>%
  fit(PC_HEALTHXP ~ PC_GDP, data = drug_spending2015) 


GDP_HC_fit
glance(GDP_HC_fit)$r.squared

```
```{r}
drug_spending2015EU <- drug_spending2015 %>%
                        filter(Continent == "Europe")
```

```{r linear-regression-2015-europe}
GDP_HC_fit_EU <- 
  linear_reg() %>%
  set_engine("lm") %>%
  fit(PC_HEALTHXP ~ PC_GDP, data = drug_spending2015EU) 


GDP_HC_fit_EU
glance(GDP_HC_fit_EU)$r.squared

```
```{r}
modelEU <- lm(PC_HEALTHXP ~ PC_GDP, data=drug_spending2015EU)
residEU <- resid(modelEU)
predictEU <- predict(modelEU)

drug_spending2015EU %>%
  ggplot(aes(x = PC_GDP, y = PC_HEALTHXP)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +     # regression line  
  geom_segment(aes(xend = PC_GDP, yend = predictEU), alpha = .2) +      # draw line from point to line
  geom_point(aes(color = abs(residEU), size = abs(residEU))) +  # size of the points
  scale_color_continuous(low = "green", high = "red") + 
  guides(color = FALSE, size = FALSE) +                             # Size legend removed
  geom_point(aes(y = predictEU), shape = 1) +
  theme_bw()
```
```{r}
standard_res <- rstandard(modelEU)
standard_res

```


```{r finding-GDP-healthXP-by-country}
drug_spending %>%
    ggplot(aes(x = Continent, y = PC_HEALTHXP, fill = Continent)) +
    geom_boxplot() +
    #facet_wrap(~TIME) + 
    theme(legend.position = "none") +
    labs(x = "Continents",
         y = "Percent of drug spending on healthcare", 
        title = "xx")
```